### ISSUE TITLE
Deployment of image on docker hub

### ISSUE THREAD

**Issue by fkromer** [phnmnl/container-pwiz#15]
Would be great if you could provide this official container on [docker hub](https://hub.docker.com/search?q=proteowizard&type=image).

**Comment by sneumann** [comment]
Hi, due to legal reasons I am hesitant to do that. The good news is that 
there is now https://hub.docker.com/r/chambm/pwiz-skyline-i-agree-to-the-vendor-licenses
developed in https://github.com/ProteoWizard/container/blob/master/Dockerfile
Yours, Steffen

**Comment by fkromer** [comment]
In the first place I misunderstood the hint in the README.md of this repository:

> Please note that there is now a container by the Proteowizard team as part of their continuous integration pipeline which should be used instead of this one: https://hub.docker.com/r/chambm/pwiz-skyline-i-agree-to-the-vendor-licenses

Thanks for clarifying this.
