### ISSUE TITLE
Docker hub?

### ISSUE THREAD

**Issue by poofcakes** [phnmnl/container-pwiz#16]
Hello,

Since you mention in your README to not use the chambm container in the docker hub, I was wondering which one we should use then? Do you guys offer your container on docker hub yet? If not, will that happen anytime soon? To build a singularity docker, which is required on the server is use, I need to be able to pull off of docker hub. Thank you!

**Comment by sneumann** [comment]
Hi, confusing wording, I have clarified now:
https://github.com/phnmnl/container-pwiz/commit/a54dce6f042959bb7bbd2c776f735dfeeb199242#diff-04c6e90faac2675aa89e2176d2eec7d8R14

Your, Steffen
