### ISSUE TITLE
Mislabeled collision energies after conversion

### ISSUE THREAD

**Issue by jmorim** [phnmnl/container-pwiz#20]
I have MRM data from an Agilent 6495 that I converted with the command
```
msconvert 0001.d --mzML --srmAsSpectra
```
Looking at the mzML file in a text editor, the collision energies are 20, 16, 12, 8, 0, 24, 18, 12, and 6. According to the instrument parameters and MassHunter Qual, they should have been 30, 24, 18, 12, 6, 20, 16, 12, 8, and 4. So 30 and 4 aren't showing up and 0 shows up from nowhere. I attached an example file
[mrm_file.zip](https://github.com/phnmnl/container-pwiz/files/12433842/mrm_file.zip)

**Comment by jmorim** [comment]
Just realized this must be something to do with the number of MRM experiments going on and the way the instrument scans through them. Looking at the data in Qual there are some cycles where it skips over CEs.

**Comment by sneumann** [comment]
Plus, please head over to https://github.com/ProteoWizard/container which is now the official upstream container. 
Yours, Steffen
