### ISSUE TITLE
Display pwiz in App Library

### ISSUE THREAD

**Issue by sh107** [phnmnl/container-pwiz#4]
Hello, I wonder if you would like this container to be included in App Library.
Thanks.

**Comment by khaug** [comment]
Is this the same version that sneumann use?

**Comment by sneumann** [comment]
I'd like it to be in Jenkins passing with test data before going AppDB. Yours, Steffen

**Comment by sneumann** [comment]
Hi, with the current version I would be happy if it ends up in the AppDB. 
@khaug or @ilveroluca , what do I have to do ? I updated the README.md 
to be conformant. Anything else I need to do ? Yours, Steffen

**Comment by kikkomep** [comment]
Hi @sneumann, @ilveroluca, @pcm32!  List of repositories has been updated in the develop branch.

**Comment by kikkomep** [comment]
... and now online on the AppLibrary of portaldev (https://portaldev.phenomenal-h2020.eu/app-library/pwiz).
