### ISSUE TITLE
Dockerfile parse error line 85: unknown instruction: INSTALL

### ISSUE THREAD

**Issue by MrDarkHorse** [phnmnl/container-pwiz#5]
Is this an issue with the Dockerfile not keeping up with the latest versions of Docker maybe?

**Comment by sneumann** [comment]
Hi, thanks for catching this. I guess this was simply missing the `RUN` statement, 
but haven't tested my fix yet. Another current issue here is that pwiz installation 
through wine requires that even the build the container is run privileged, 
so you might run into that as well. 
Yours, Steffen

**Comment by MrDarkHorse** [comment]
I actually came to that conclusion myself, but then got other errors.  I'm motivated to get this working, so I'll take another look tonight to see what my latest issues are.

I'm trying this on a Macbook Pro, so I'm interested to see if I can get a working docker solution to convert windows based files (like Thermo .raw) to mzml.

**Comment by sneumann** [comment]
I think this was fixed long ago. Yours, Steffen
